modLoader="javafml" #mandatory
loaderVersion="[41,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All Rights Reserved"
issueTrackerURL=""

[[mods]] #mandatory
modId="more_interactions" #mandatory
version="1.19-2.0.0" #mandatory
displayName="Interactions" #mandatory
displayURL="https://www.curseforge.com/minecraft/mc-mods/more_interactions"
logoFile="logo.png" #optional
authors="ISenseHostility" #optional
description='''
    More Interactions adds a bunch of small vanilla-style interactions.
    '''

[[dependencies.more_interactions]]
modId="forge"
mandatory=true
versionRange="[41,)"
ordering="NONE"
side="BOTH"

[[dependencies.more_interactions]]
modId="minecraft"
mandatory=true
versionRange="[1.19,)"
ordering="NONE"
side="BOTH"
